server:
  port: 8000

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway

# Configurações dos serviços
services:
  auth:
    url: "${SERVICES_AUTH_URL:http://localhost:8000}"
  usuario:
    url: "${SERVICES_USUARIO_URL:http://localhost:8080}"
  pedido:
    url: "${SERVICES_PEDIDO_URL:http://localhost:8081}"
  rastreamento:
    url: "${SERVICES_RASTREAMENTO_URL:http://localhost:8082}"
  notificacao:
    url: "${SERVICES_NOTIFICACAO_URL:http://localhost:8083}"

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: swagger-ui-route
          uri: http://localhost:${server.port}
          predicates:
            - Path=/swagger-ui/**,/v3/api-docs/**,/swagger-resources/**,/webjars/**

        - id: auth-service
          uri: ${SERVICES_USUARIO_URL:http://localhost:8000}
          predicates:
            - Path=/api/auth/**
          filters:
            - AddRequestHeader=X-Internal-Auth,2BE2AB6217329B86A427A3819B626

        - id: usuario-service
          uri: ${SERVICES_USUARIO_URL:http://localhost:8080}
          predicates:
            - Path=/api/usuarios/**
          filters:
            - AddRequestHeader=X-Internal-Auth,2BE2AB6217329B86A427A3819B626
        - id: usuario-registro-service
          uri: ${SERVICES_USUARIO_URL:http://localhost:8080}
          predicates:
            - Path=/api/registro/usuarios/**
          filters:
            - AddRequestHeader=X-Internal-Auth,2BE2AB6217329B86A427A3819B626

        - id: pedido-service
          uri: ${SERVICES_PEDIDO_URL:http://localhost:8081}
          predicates:
            - Path=/api/pedidos/**
          filters:
            - AddRequestHeader=X-Internal-Auth,2BE2AB6217329B86A427A3819B626

        - id: rastreamento-service
          uri: ${SERVICES_RASTREAMENTO_URL:http://localhost:8082}
          predicates:
            - Path=/api/rastreamento/**
          filters:
            - AddRequestHeader=X-Internal-Auth,2BE2AB6217329B86A427A3819B626

        - id: notificacao-service
          uri: ${SERVICES_NOTIFICACAO_URL:http://localhost:8083}
          predicates:
            - Path=/api/notificacoes/**
          filters:
            - AddRequestHeader=X-Internal-Auth,2BE2AB6217329B86A427A3819B626
        - id: notificacao-websocket
          uri: ws://notificacao-service:8083
          predicates:
            - Path=/ws-notificacao/**
          filters:
            - AddRequestHeader=X-Internal-Auth,2BE2AB6217329B86A427A3819B626

      # Configurações globais
      default-filters:
        - name: RequestSize
          args:
            maxSize: 5MB

# Configuração de segurança
security:
  jwt:
    secret: a36cac71d1a44a1593a22d98403455bd2d6f737e465c4cf3fcead29381a08335
    expiration: 86400
  internal:
    header-name: X-Internal-Auth
    header-value: 2BE2AB6217329B86A427A3819B626

# Configuração de logging
logging:
  level:
    org.springframework.security: TRACE
    org.springframework.web.reactive.function.client: DEBUG
    org.springframework.cloud.gateway: INFO
    reactor.netty: INFO
    com.logistica.apigateway: DEBUG
