server:
  port: 8080
  address: 0.0.0.0  # Aceita apenas conexões locais (mesmo host)
  # OU address: 192.168.1.100  # Aceita apenas conexões do endereço IP específico da rede interna
security:
  internal:
    header-name: X-Internal-Auth
    header-value: 2BE2AB6217329B86A427A3819B626
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/main_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

rabbitmq:
  exchange: logisticaExchange

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  packages-to-scan: com.logistica.usuario.controller


