server:
  port: 8082
  address: 0.0.0.0  # Aceita apenas conexões locais (mesmo host)
  # OU address: 192.168.1.100  # Aceita apenas conexões do endereço IP específico da rede interna
security:
  internal:
    header-name: X-Internal-Auth
    header-value: 2BE2AB6217329B86A427A3819B626
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/main_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

rabbitmq:
#  queue: pedidosQueue
#  exchange: pedidosExchange
#  routingkey: pedidosRoutingKey
  exchange: logistica.exchange

# Configurações do gRPC
grpc:
  server:
    port: 9090

# Configurações para outros serviços
services:
  pedido:
    url: "${PEDIDOS_SERVICE_URL:http://localhost:8081}"
  usuario:
    url: "${USUARIO_SERVICE_URL:http://localhost:8080}"

logging:
  level:
    com.logistica.pedidos: DEBUG
    org.springframework.amqp: INFO

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
