server:
  port: 8083
  address: 0.0.0.0  # Aceita apenas conexões locais (mesmo host)
  # OU address: 192.168.1.100  # Aceita apenas conexões do endereço IP específico da rede interna
services:
  usuario:
    url: "${USUARIO_SERVICE_URL:http://localhost:8080}"
security:
  internal:
    header-name: X-Internal-Auth
    header-value: 2BE2AB6217329B86A427A3819B626
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/main_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
aws:
  region: us-east-1
  sqs:
    email-queue-url: ${AWS_SQS_EMAIL_QUEUE_URL:https://sqs.us-east-1.amazonaws.com/176343551411/email-notifications}
  trigger:
    url: https://ceqvslj8df.execute-api.us-east-1.amazonaws.com/prod/campanhas/trigger
rabbitmq:
  exchange: logistica.exchange

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.logistica.notificacoes: DEBUG
    org.springframework.amqp: INFO
    org.springframework: DEBUG
    org.springframework.web: DEBUG
    org.springdoc: DEBUG
